### ISSUE TITLE
ModuleNotFoundError: No module named 'xerparser.dcma14'

### ISSUE THREAD

**Issue by rfdiazpr** [HassanEmam/PyP6Xer#14]
Error running the test.py

from xerparser.dcma14 import DCMA14
ModuleNotFoundError: No module named 'xerparser.dcma14'
WinPython -> Python 3.9.5

**Comment by HassanEmam** [comment]
Hi @rfdiazpr 

Well the DCMA14 analysis was not part of the package as it is still WIP and has not been tested properly
However, I have included it in an updated package that I published today

Try to install the latest version using 
```bash
pip install --upgrade PyP6Xer
```
This should fix the error.

Please let me know if it did work to close this issue.

Thanks

**Comment by rfdiazpr** [comment]
@HassanEmam 
Yes. Thanks.
