### ISSUE TITLE
end_date showing wrong values

### ISSUE THREAD

**Issue by chehadekassouf** [HassanEmam/PyP6Xer#2]
I noticed that the end_date is showing the same value as start_date.
I had to use the early_end_date for the meantime.

**Comment by HassanEmam** [comment]
Thanks for the feedback. Would you please share your code to reproduce the issue and fix it.

**Comment by chehadekassouf** [comment]
![image](https://user-images.githubusercontent.com/9428798/102999916-a42c9a80-4532-11eb-9903-c0e35123ac11.png)
I hope this screen shot clarify the issue.
