### ISSUE TITLE
Reader.resources is empty

### ISSUE THREAD

**Issue by chehadekassouf** [HassanEmam/PyP6Xer#3]
The resources are not being loaded.
I tried both Reader and to reach it from within activity. resources but the it contained only resource assignment primitive information.
example is labor or not.
Is it possible to add the resource object to the individual resource assignment at the activity level

**Comment by HassanEmam** [comment]
The resources object contains resources dictionary. For resources assignment use the activityresources

**Comment by chehadekassouf** [comment]
Thank you for the quick feedback
the resources object resolve the first part of my question.
However in the activity resources I don't have a link back to the resources object, what i have is BL_QTY,ACT_QTY,REM_QTY.
if you can add one more property to reference the corresponding resource object this would be great
